### ISSUE TITLE
Support secure connection to Kafka

### ISSUE THREAD

**Issue by ericbottard** [bsideup/liiklus#218]
TBD, but I think this should at least encompass TLS transport configurability as well as 2-way certificate authentication.

Bonus points for making this as k8s friendly as possible.

**Comment by bsideup** [comment]
We can gain some inspiration from Pulsar's TLS support:
https://github.com/bsideup/liiklus/pull/158

**Comment by bsideup** [comment]
Kafka properties support was added in #387. The following config can be used:
```properties
kafka.bootstrapServers=kafka:9092

kafka.properties[security.protocol]=SASL_SSL
kafka.properties[ssl.endpoint.identification.algorithm]=https

kafka.properties[sasl.mechanism]=PLAIN
kafka.properties[sasl.jaas.config]=org.apache.kafka.common.security.plain.PlainLoginModule   required username="XXX"   password="XXX";
```
