### ISSUE TITLE
Support some concept of "interceptor"

### ISSUE THREAD

**Issue by ericbottard** [bsideup/liiklus#221]
Maybe this is already achievable via the concept of plugins, but it would be helpful to have the ability to "intercept" data being published to a topic.

For example, for the purposes of [riff](http://github.com/projectriff), it would be nice to be able to assess the format of data being published to topics, and validate that it is actually conforming to the riff encoding model.

**Comment by bsideup** [comment]
Take a look at https://github.com/bsideup/liiklus/blob/master/examples/plugin/src/main/java/com/github/bsideup/liiklus/plugins/example/ExampleRecordPreProcessor.java

There is also a schema plugin (currently only JSON schema is supported):
https://github.com/bsideup/liiklus/tree/master/plugins/schema

**Comment by ericbottard** [comment]
Nice!

We would still need a way to handle shared state that only riff knows about, but I think this answers the question about "inceptors" being available. Closing this, thanks!
