### ISSUE TITLE
Loosing the key on pulsar message send

### ISSUE THREAD

**Issue by lanwen** [bsideup/liiklus#348]
https://github.com/bsideup/liiklus/blob/master/plugins/pulsar-records-storage/src/main/java/com/github/bsideup/liiklus/pulsar/PulsarRecordsStorage.java#L88

here we get ByteBuffer at the end position, which produces empty string on decode - should be rewind, but have to check if we won't introduce any memleaks here

**Comment by lanwen** [comment]
Seems my fault - in a pre-processor I'm reading the key without duplication, which breaks position in the records storage. 

So maybe a good measure to do rewind on a duplicated key, to avoid that kind of issues and side effects from other plugins?

**Comment by bsideup** [comment]
@lanwen rewind here is an assumption that shouldn't be made. Unfortunately, that's how ByteBuffer JDK API is defined and the users are responsible for not "mutating" the buffers that should not be.
