### ISSUE TITLE
Reactive-gRPC 0.10.0-RC1

### ISSUE THREAD

**Issue by rmichela** [bsideup/liiklus#98]
Hello. We've released Reactive-gRPC 0.10.0-RC1. Would you be willing to try it out and report any findings?

https://github.com/salesforce/reactive-grpc/releases/tag/v0.10.0-RC1

**Comment by bsideup** [comment]
Hi @rmichela,

Sorry for taking sooooo long :) I confirm that at least the tests pass with 0.10.0 (release) 🎉
I will request production evaluation from one of the companies that uses Liiklus in prod to verify that it works from them too 👍
